name: react_dev

on:
  push:
    branches:
      - main
      - dev
      - stage
      
  workflow_dispatch:

jobs:
  DELIVERY:
    name: Push para docker Hub
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.USER  }}
            password: ${{ secrets.PASSWD  }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build Docker Image
          env:
              NODE_ENV: production  # Defina aqui a variável de ambiente
          run: |
           docker build --build-arg NODE_ENV=${NODE_ENV} -t my-app .

        - name: Push Docker Image
          run: |
            echo "Implement your Docker push command here if needed"














